# Generated by Django 4.2.2 on 2023-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_clothes_description_alter_clothes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothe/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='clothes',
        ),
    ]
