# Generated by Django 4.2.2 on 2023-07-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_clothe_delete_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='product1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothe/%Y/%m/%d')),
            ],
        ),
    ]
